#!/bin/sh
set -eu

ROOT="$(dirname "$0")/.."
cd "$ROOT"

python3 -m pytest -q \
  tests/test_quant_binance_core.py::QuantBinanceCoreTests::test_build_executive_operating_verdict_prefers_staged_candidate_bucket_for_expansion_evidence \
  tests/test_quant_binance_core.py::QuantBinanceCoreTests::test_build_executive_operating_verdict_rebuilds_when_checkpoint_expand_lacks_bucket_source \
  tests/test_quant_binance_checkpoint_auto_judge.py::QuantBinanceCheckpointAutoJudgeTests::test_checkpoint_auto_judge_prefers_staged_candidate_bucket_execution_metrics \
  tests/test_quant_binance_checkpoint_auto_judge.py::QuantBinanceCheckpointAutoJudgeTests::test_strategy_proposal_requires_bucket_expansion_evidence_before_ready \
  tests/test_quant_binance_validation_report.py::QuantBinanceValidationReportTests::test_build_policy_comparison_validation_artifact_requires_bucket_replay_before_simple_baseline_passes \
  tests/test_quant_binance_validation_report.py::QuantBinanceValidationReportTests::test_build_policy_comparison_validation_artifact_uses_latest_bucket_logs_for_current_policy_replay \
  tests/test_quant_binance_execution_quality_report.py::QuantBinanceExecutionQualityReportTests::test_build_execution_quality_report_aggregates_orders_errors_and_validation_evidence \
  tests/test_quant_binance_telegram_reports.py::QuantBinanceTelegramReportsTests::test_format_execution_quality_report_in_korean
