@echo off
set "QUANT_READ_ONLY_PAPER_MODE=1"
set "QUANT_PAPER_VERIFY_EQUITY_USD=50"
set "QUANT_PAPER_VERIFY_USE_CAPPED_ENTRY=1"
set "QUANT_PAPER_VERIFY_STOP_ON_KILL_SWITCH=0"
set "QUANT_BYPASS_POLICY_GUARDRAILS=1"
set "QUANT_BINANCE_ALLOW_FILE_RUNTIME_OVERRIDES=0"
set "STRATEGY_OVERRIDE_PATH=quant_runtime_paper50/paper50_multi_symbol_filters.json"
set "STRATEGY_PROFILE=live-ultra-aggressive"
set "UNIVERSE_SYMBOLS=PEPEUSDT,DOGEUSDT,XRPUSDT,SOLUSDT,ETHUSDT,BTCUSDT"
set "QUANT_TELEGRAM_NOTIFICATIONS=0"
set "SELF_HEAL_MAX_STALL_RESTARTS=999"
set "HTTP_PROXY="
set "HTTPS_PROXY="
set "ALL_PROXY="
set "GIT_HTTP_PROXY="
set "GIT_HTTPS_PROXY="
set "http_proxy="
set "https_proxy="
set "all_proxy="
set "NO_PROXY=*"
set "no_proxy=*"
cd /d "C:\Users\SSAFY\Downloads\first_repo-main"
python -m quant_binance.runtime --mode live-paper-daemon --exchange bitget --output-base quant_runtime_paper50 --max-retries 999999 --sync-interval-seconds 60 --insecure-ssl 1>> "C:\Users\SSAFY\Downloads\first_repo-main\quant_runtime_paper50\_paper50.out.log" 2>> "C:\Users\SSAFY\Downloads\first_repo-main\quant_runtime_paper50\_paper50.err.log"
